name: crm_app
description: "Una app CRM"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  animate_do: ^3.3.4
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  floating_action_bubble_custom: ^1.0.0+2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.4.10
  flutter_spinkit: ^5.2.0
  flutter_staggered_grid_view: ^0.7.0
  formz: ^0.6.1
  go_router: ^13.1.0
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  syncfusion_flutter_calendar: ^24.2.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/loaders/
    - assets/images/
    - google_fonts/montserrat_alternates/
